[package]
name = "iris_nn"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1"
serde = { version="1", features=["derive"] }
serde_derive = "1"
libm = "0.2.1"
rand = "0.8.4"